export const BOOKMARK_NAMESPACE = "explorerBookmarkTree";
export const BOOKMARK_TREE_VIEW_ID = BOOKMARK_NAMESPACE;
export const BOOKMARK_VIEW_MODE_CONTEXT_KEY = `${BOOKMARK_NAMESPACE}:viewMode`;
export const BOOKMARK_HAS_BOOKMARKS_CONTEXT_KEY = `${BOOKMARK_NAMESPACE}:hasBookmarks`;
export const BOOKMARK_EXPAND_COLLAPSE_ACTION_CONTEXT_KEY = `${BOOKMARK_NAMESPACE}:expandCollapseAction`;
